version: "3.9"

services:
  qqnt:
    image: catlair/qqnt

    security_opt:
      - seccomp:unconfined

    # Or build locally
    # build: .

    deploy:
      restart_policy:
        condition: on-failure

    environment:
      - VNC_PASSWD=password

    ports:
      - "80:80"
      - "5901:5901"
