version: "3.9"

services:
  qqnt:
    image: catlair/qqnt:0.0.2

    security_opt:
      - seccomp:unconfined

    # Or build locally
    # build: .

    deploy:
      restart_policy:
        condition: on-failure

    ports:
      - "80:80"
      - "5901:5901"
