name: Push

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  push:
    name: Push

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # - name: Prepare Tag
      #   id: tag
      #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
      #   run: |
      #     VERSION="${GITHUB_REF##refs/tags/}"
      #     echo "Found Tag: ${VERSION}"
      #     echo "version=${VERSION}" >> $GITHUB_OUTPUT
      #   shell: bash

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          build-args: |
            BUILD_ARCH=amd64
            BUILD_QQNT_LINK=https://dldir1.qq.com/qqfile/qq/QQNT/fd2e886e/linuxqq_3.2.2-18394
          tags: |
            catlair/qqnt:latest
            ghcr.io/catlair/qqnt:latest
